line-length = 100

[lint]
exclude = ["src/**/protobuf/**"]
select = [
    "ANN",
    "E4",
    "E7",
    "E9",
    "F",
    "UP",
    "S110",
    "S112",
    "S603",
    "S604",
    "B",
    "A",
    "C4",
    "DTZ",
    "ISC",
    "LOG",
    "INP",
    "PIE",
    "Q",
    "SIM",
    "ARG"
]
ignore = [
    "ANN204",
    "UP017",
    "C401",
    "SIM108",
    "SIM300"
]

[lint.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true
suppress-dummy-args = true

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

exclude = ["src/**/protobuf/**"]
