[lint]
exclude = ["src/**/protobuf/**"]
select = [
    "ANN",
    "E4",
    "E7",
    "E9",
    "F",
    "UP",
]
ignore = [
    "ANN204",
    "UP017"
]

[lint.flake8-annotations]
mypy-init-return = true
suppress-none-returning = true
suppress-dummy-args = true

[format]
quote-style = "single"
docstring-code-format = true
exclude = ["src/**/protobuf/**"]
