import React, { useCallback, useEffect, useState } from 'react';
import { useSortBy, useTable, usePagination } from 'react-table';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TableSortLabel,
  TablePagination,
  CircularProgress,
} from '@material-ui/core';
import { makeStyles, darken } from '@material-ui/core/styles';

import TablePaginationActions from './TablePaginationActions';
import { useEditable } from './useEditable';

const useStyles = makeStyles((theme) => ({
  editCell: {
    display: 'flex',
    justifyContent: 'center',
  },
  tableHead: {
    backgroundColor: darken(theme.palette.background.paper, 0.1),
  },
  pagination: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
}));

/**
 * Renders a table with data generated by react-table with custom hooks
 */
export default function MaterialTable(props) {
  const {
    columns,
    data,
    sortable = false,
    editable = false,
    deletable = false,
    pagination = false,
    rowsPerPage: rowsPerPageInitial = 25,
    onSaveRow,
    onDeleteRow,
    id,
    fetchData,
    rowCount = 0,
    loading = false,
  } = props;

  if (data === null || data === undefined) {
    throw new TypeError('Data not given to table');
  }

  const classes = useStyles();
  const [rowsPerPage] = useState(rowsPerPageInitial);

  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    tableSize,
    prepareRow,
    setPageSize,
    gotoPage,
    state: { pageIndex, pageSize },
  } = useTable({
    columns,
    data,
    disableSortBy: !sortable,
    disableDeleting: !deletable,
    disableEditing: !editable,
    classes,
    onSaveRow,
    onDeleteRow,
    initialState: {
      pageSize: rowsPerPage,
    },
    manualPagination: true,
    pageCount: -1, // This is handled by the TablePagination component
    autoResetPage: false,
  },
  useSortBy,
  useEditable,
  usePagination);

  useEffect(() => {
    if (typeof fetchData !== 'function') return;

    fetchData(pageIndex, pageSize);
  }, [fetchData, pageIndex, pageSize]);

  const onChangePage = useCallback((e, page) => {
    gotoPage(page);
  }, [gotoPage]);
  const onChangePageSize = useCallback((e) => setPageSize(e.target.value), [setPageSize]);
  const labelDisplayedRows = useCallback(
    ({ page }) => `Page ${page+1} of ${Math.ceil(rowCount/pageSize)}`, [pageSize, rowCount]
  );

  return (
    <div id={id}>
      <Table
        size={tableSize}
        {...getTableProps()}
      >
        <TableHead className={classes.tableHead}>
          {headerGroups.map(headerGroup => (
            <TableRow {...headerGroup.getHeaderGroupProps()}>
              {headerGroup.headers.map(col => (
                <TableCell
                  {...col.getHeaderProps(col.getSortByToggleProps({ width: col.widthSuggestion }))}
                >
                  {col.canSort ? (
                    <TableSortLabel
                      active={col.isSorted}
                      direction={col.isSortedDesc ? 'desc' : 'asc'}
                      hideSortIcon={!sortable}
                    >
                      {col.render('Header')}
                    </TableSortLabel>
                  ) : col.render('Header')}
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableHead>
        <TableBody {...getTableBodyProps()}>
          {rows.map(row => {
            prepareRow(row);
            return (
              <TableRow {...row.getRowProps()}>
                {row.cells.map(cell => (
                  <TableCell
                    padding={cell.column.padding}
                    {...cell.getCellProps()}
                  >
                    {cell.render('Cell')}
                  </TableCell>
                ))}
              </TableRow>
            );
          })}
        </TableBody>
      </Table>
      {pagination && (
        <div className={classes.pagination}>
          {loading && <CircularProgress size={30} />}
          <TablePagination
            component='div'
            count={rowCount}
            page={pageIndex}
            rowsPerPage={pageSize}
            onChangePage={onChangePage}
            onChangeRowsPerPage={onChangePageSize}
            ActionsComponent={TablePaginationActions}
            labelDisplayedRows={labelDisplayedRows}
          />
        </div>
      )}
    </div>
  );
}
