import React, {
  ComponentType,
  ReactElement,
  useCallback,
  useMemo,
} from 'react';
import {
  type LabelDisplayedRowsArgs,
  type SxProps,
  CircularProgress,
  Skeleton,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TablePagination,
  TableRow,
  TableSortLabel,
} from '@mui/material';
import { styled } from '@mui/material/styles';
import {
  type Column,
  type ReactTable,
  RowData,
  TableFeatures,
} from '@tanstack/react-table';

import { noop } from '@/webUtils/utilities';

import { CSS_CLASSES } from './constants';
import { MaterialTableRow } from './MaterialTableRow';
import type { WithRequiredFeature } from './plugins/types';
import TablePaginationActions from './TablePaginationActions';
import {
  DialogComponentProps,
  TableToolbar,
  TableToolbarProps,
} from './TableToolbar';
import { doIfColumnFeatureExists, doIfTableFeatureExists } from './utilities';


const TableHeadStyled = styled(TableHead)(({ theme }) => ({
  backgroundColor: theme.vars.palette.background.paper,
  [theme.getColorSchemeSelector('light')]: {
    filter: 'brightness(0.95)',
  },
}));

const PaginationContainer = styled('div')({
  display: 'flex',
  justifyContent: 'flex-end',
  alignItems: 'center',
});

const Root = styled('div')({
  [`& .${CSS_CLASSES.editCell}`]: {
    display: 'flex',
    justifyContent: 'center',
  },
});

const skeletonCount = new Array(10).fill(0);

function getCssWidth(width: number | string | undefined): string | undefined {
  if (typeof width === 'number') {
    return `${width}px`;
  }

  return width;
}


export type MaterialTableProps<
  TFeatures extends TableFeatures,
  TData extends RowData,
  TSelected
> = {
  table: ReactTable<TFeatures, TData, TSelected>
  title?: string
  ariaLabel?: string
  id?: string
  /* Number of rows in a paginated table and number of skeleton rows while loading */
  rowCount?: number
  loading?: boolean
  CreateDialog?: ComponentType<DialogComponentProps>
  toolbarProps?: TableToolbarProps
  enableRowCreation?: boolean
  sx?: SxProps
};

/**
 * Renders a table with data generated by react-table with custom hooks
 */
export const MaterialTable = <
  TFeatures extends TableFeatures,
  TData extends RowData,
  TSelected
>(
  props: MaterialTableProps<TFeatures, TData, TSelected>
): ReactElement => {
  const {
    table,
    title,
    ariaLabel,
    id,
    rowCount = 0,
    loading = false,
    CreateDialog,
    toolbarProps,
    enableRowCreation = false,
    sx,
  } = props;

  const skeletonArray = useMemo(() => {
    if (rowCount > 0) return new Array(rowCount).fill(0);

    return skeletonCount;
  }, [rowCount]);

  const onChangePage = useMemo(
    () =>
      doIfTableFeatureExists(
        'rowPaginationFeature',
        table,
        table => (_: unknown, page: number) => {
          table.setPageIndex(page);
        },
        () => noop
      ),
    [table]
  );

  const onChangePageSize: React.ChangeEventHandler<HTMLTextAreaElement | HTMLInputElement> = useMemo(
    () => doIfTableFeatureExists(
      'rowPaginationFeature',
      table,
      table => (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
        table.setPageSize(Number(e.target.value));
      },
      () => noop
    ),
    [table]
  );
  const labelDisplayedRows = useCallback(
    ({
      page,
    }: LabelDisplayedRowsArgs) => {
      const pageSize = (
        table as unknown as ReactTable<WithRequiredFeature<'rowPaginationFeature'>, TData>
      ).atoms.pagination.get().pageSize;

      return `Page ${page + 1} of ${Math.ceil(rowCount / pageSize)}`;
    },
    [rowCount, table]
  );

  return (
    <Root id={id} sx={sx}>
      <TableToolbar
        title={title}
        DialogComponent={CreateDialog}
        creatable={enableRowCreation}
        {...toolbarProps}
      />
      <Table
        aria-label={ariaLabel ?? title}
        data-isloading={loading}
      >
        <colgroup>
          {table.getAllFlatColumns().map(col => (
            <col
              style={{
                width: getCssWidth((col as Column<WithRequiredFeature<'coreRowsFeature'>, TData>).columnDef.meta?.width),
                minWidth: getCssWidth((col as Column<WithRequiredFeature<'coreRowsFeature'>, TData>).columnDef.meta?.minWidth),
              }}
              key={col.id}
            />
          ))}
        </colgroup>

        <TableHeadStyled>
          {table.getHeaderGroups().map(headerGroup => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map(header => {
                return doIfColumnFeatureExists(
                  'rowSortingFeature',
                  header.column,
                  col => (
                    <TableCell
                      key={header.id}
                      colSpan={header.colSpan}
                      sortDirection={col.getIsSorted() || undefined}
                    >
                      {col.getCanSort()
                        ? (
                          <TableSortLabel
                            active={col.getIsSorted() !== false}
                            direction={col.getIsSorted() || 'desc'}
                            onClick={col.getToggleSortingHandler()}
                          >
                            <table.FlexRender header={header} />
                          </TableSortLabel>
                        )
                        : <table.FlexRender header={header} />}
                    </TableCell>
                  ),

                  () => (
                    <TableCell
                      key={header.id}
                      colSpan={header.colSpan}
                    >
                      <table.FlexRender header={header} />
                    </TableCell>
                  )
                );
              })}
            </TableRow>
          ))}
        </TableHeadStyled>

        <TableBody aria-live='polite'>
          {loading && !table.getRowModel().rows.length && skeletonArray.map((_, i) => (
            <TableRow key={i} aria-hidden>
              {table.getHeaderGroups()[0].headers.map(h => (
                <TableCell key={h.id} sx={{ fontSize: '1.2rem' }}>
                  <Skeleton />
                </TableCell>
              ))}
            </TableRow>
          ))}
          {table.getRowModel().rows.map(row => {
            return <MaterialTableRow key={row.id} row={row} />;
          })}
        </TableBody>
      </Table>

      {doIfTableFeatureExists(
        'rowPaginationFeature',
        table,
        table => (
          <PaginationContainer>
            {loading && <CircularProgress size={30} aria-label='Loading icon' />}
            <table.Subscribe
              selector={state => ({
                pagination: state.pagination,
              })}
            >
              {({ pagination }) => (
                <TablePagination
                  component='nav'
                  count={rowCount}
                  page={pagination.pageIndex}
                  rowsPerPage={pagination.pageSize}
                  onPageChange={onChangePage}
                  onRowsPerPageChange={onChangePageSize}
                  ActionsComponent={TablePaginationActions}
                  labelDisplayedRows={labelDisplayedRows}
                  aria-label='Table pagination'
                />
              )}
            </table.Subscribe>
          </PaginationContainer>
        )
      )}
    </Root>
  );
};
