/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowsRouteImport } from './routes/follows'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MangaMangaIdRouteImport } from './routes/manga/$mangaId'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as staticThird_party_noticesRouteImport } from './routes/(static)/third_party_notices'
import { Route as staticTermsRouteImport } from './routes/(static)/terms'
import { Route as staticPrivacy_policyRouteImport } from './routes/(static)/privacy_policy'
import { Route as AdminMangaMergeRouteImport } from './routes/admin/manga.merge'
import { Route as AdminMangaMangaIdRouteImport } from './routes/admin/manga.$mangaId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowsRoute = FollowsRouteImport.update({
  id: '/follows',
  path: '/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaMangaIdRoute = MangaMangaIdRouteImport.update({
  id: '/manga/$mangaId',
  path: '/manga/$mangaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const staticThird_party_noticesRoute =
  staticThird_party_noticesRouteImport.update({
    id: '/(static)/third_party_notices',
    path: '/third_party_notices',
    getParentRoute: () => rootRouteImport,
  } as any)
const staticTermsRoute = staticTermsRouteImport.update({
  id: '/(static)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const staticPrivacy_policyRoute = staticPrivacy_policyRouteImport.update({
  id: '/(static)/privacy_policy',
  path: '/privacy_policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMangaMergeRoute = AdminMangaMergeRouteImport.update({
  id: '/admin/manga/merge',
  path: '/admin/manga/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMangaMangaIdRoute = AdminMangaMangaIdRouteImport.update({
  id: '/admin/manga/$mangaId',
  path: '/admin/manga/$mangaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/follows': typeof FollowsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/privacy_policy': typeof staticPrivacy_policyRoute
  '/terms': typeof staticTermsRoute
  '/third_party_notices': typeof staticThird_party_noticesRoute
  '/admin/services': typeof AdminServicesRoute
  '/manga/$mangaId': typeof MangaMangaIdRoute
  '/admin/manga/$mangaId': typeof AdminMangaMangaIdRoute
  '/admin/manga/merge': typeof AdminMangaMergeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follows': typeof FollowsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/privacy_policy': typeof staticPrivacy_policyRoute
  '/terms': typeof staticTermsRoute
  '/third_party_notices': typeof staticThird_party_noticesRoute
  '/admin/services': typeof AdminServicesRoute
  '/manga/$mangaId': typeof MangaMangaIdRoute
  '/admin/manga/$mangaId': typeof AdminMangaMangaIdRoute
  '/admin/manga/merge': typeof AdminMangaMergeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/follows': typeof FollowsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/(static)/privacy_policy': typeof staticPrivacy_policyRoute
  '/(static)/terms': typeof staticTermsRoute
  '/(static)/third_party_notices': typeof staticThird_party_noticesRoute
  '/admin/services': typeof AdminServicesRoute
  '/manga/$mangaId': typeof MangaMangaIdRoute
  '/admin/manga/$mangaId': typeof AdminMangaMangaIdRoute
  '/admin/manga/merge': typeof AdminMangaMergeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/follows'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/privacy_policy'
    | '/terms'
    | '/third_party_notices'
    | '/admin/services'
    | '/manga/$mangaId'
    | '/admin/manga/$mangaId'
    | '/admin/manga/merge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/follows'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/privacy_policy'
    | '/terms'
    | '/third_party_notices'
    | '/admin/services'
    | '/manga/$mangaId'
    | '/admin/manga/$mangaId'
    | '/admin/manga/merge'
  id:
    | '__root__'
    | '/'
    | '/follows'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/(static)/privacy_policy'
    | '/(static)/terms'
    | '/(static)/third_party_notices'
    | '/admin/services'
    | '/manga/$mangaId'
    | '/admin/manga/$mangaId'
    | '/admin/manga/merge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowsRoute: typeof FollowsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  staticPrivacy_policyRoute: typeof staticPrivacy_policyRoute
  staticTermsRoute: typeof staticTermsRoute
  staticThird_party_noticesRoute: typeof staticThird_party_noticesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  MangaMangaIdRoute: typeof MangaMangaIdRoute
  AdminMangaMangaIdRoute: typeof AdminMangaMangaIdRoute
  AdminMangaMergeRoute: typeof AdminMangaMergeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follows': {
      id: '/follows'
      path: '/follows'
      fullPath: '/follows'
      preLoaderRoute: typeof FollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$mangaId': {
      id: '/manga/$mangaId'
      path: '/manga/$mangaId'
      fullPath: '/manga/$mangaId'
      preLoaderRoute: typeof MangaMangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/third_party_notices': {
      id: '/(static)/third_party_notices'
      path: '/third_party_notices'
      fullPath: '/third_party_notices'
      preLoaderRoute: typeof staticThird_party_noticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/terms': {
      id: '/(static)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof staticTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/privacy_policy': {
      id: '/(static)/privacy_policy'
      path: '/privacy_policy'
      fullPath: '/privacy_policy'
      preLoaderRoute: typeof staticPrivacy_policyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manga/merge': {
      id: '/admin/manga/merge'
      path: '/admin/manga/merge'
      fullPath: '/admin/manga/merge'
      preLoaderRoute: typeof AdminMangaMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manga/$mangaId': {
      id: '/admin/manga/$mangaId'
      path: '/admin/manga/$mangaId'
      fullPath: '/admin/manga/$mangaId'
      preLoaderRoute: typeof AdminMangaMangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowsRoute: FollowsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  staticPrivacy_policyRoute: staticPrivacy_policyRoute,
  staticTermsRoute: staticTermsRoute,
  staticThird_party_noticesRoute: staticThird_party_noticesRoute,
  AdminServicesRoute: AdminServicesRoute,
  MangaMangaIdRoute: MangaMangaIdRoute,
  AdminMangaMangaIdRoute: AdminMangaMangaIdRoute,
  AdminMangaMergeRoute: AdminMangaMergeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
